[package]
name = "vulcano_test"
version = "0.1.0"
authors = ["Erik Funder Carstensen <fundererik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.19.0"